---
sudo: false
language: python
python:
- '3.5'
install: pip3 install -r requirements.txt
cache:
- pip
script:
- python3 _schemas/tools/validate.py bills
- python3 _schemas/tools/validate.py committee_reports
- python3 _schemas/tools/validate.py electoral_districts
- python3 _schemas/tools/validate.py mps
- python3 _schemas/tools/validate.py parties _schemas/party.yaml
- python3 _schemas/tools/validate.py plenary_sittings
- python3 _schemas/tools/validate.py questions
notifications:
  email: false
